//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibbiTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastalikBilgisi
    {
        public int HastalikID { get; set; }
        public string HastalikAdi { get; set; }
        public Nullable<System.DateTime> TeşhisTarihi { get; set; }
        public string Tedavi { get; set; }
        public string TCKimlikNo { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
