//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibbiTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlacBilgisi
    {
        public int IlacID { get; set; }
        public string IlacAdi { get; set; }
        public string Dozaj { get; set; }
        public string Frekans { get; set; }
        public string TCKimlikNo { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
