//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TibbiTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TahlilBilgisi
    {
        public int TahlilID { get; set; }
        public string TahlilAdi { get; set; }
        public Nullable<System.DateTime> TahlilTarihi { get; set; }
        public string Sonuc { get; set; }
        public string TCKimlikNo { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
